server:
  port: 8081
dubbo:
  application:
    name: provider
  registry:
    address: 192.168.15.133:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
    threads: 50
  provider:
    timeout: 10000
    